import React, {useContext} from "react";
import xprt_bg from "../../assets/images1/xprt_bg.svg";
import {Accordion, Card, useAccordionToggle, AccordionContext} from "react-bootstrap";
import Icon from "../../components/Icon";

function ContextAwareToggle({children, eventKey, callback}) {
    const currentEventKey = useContext(AccordionContext);

    const decoratedOnClick = useAccordionToggle(
        eventKey,
        () => callback && callback(eventKey),
    );

    const isCurrentEventKey = currentEventKey === eventKey;

    return (
        <button
            type="button"
            className="accordion-button"
            onClick={decoratedOnClick}
        >
            <Icon viewClass="icon" icon={isCurrentEventKey ? "minus" : "plus"}/>

        </button>
    );
}

const Xprt = () => {
    return (
        <>
            <section className="xprt-section">
                <div className="container">
                    <h3 className="section-title">XPRT Token</h3>
                    <div className="row">
                        <div className="col-md-6">
                            <div className="info">
                                <p>The XPRT token is primarily a governance token for the Persistence chain. Once the
                                    Persistence mainnet is launched, token holders will be able to stake XPRT tokens to
                                    passively earn more XPRT. XPRT token also plays the role of a ‘work token’, allowing
                                    the stakers to produce cash flows in correlation with the transaction volume
                                    generated by dApps in the Persistence ecosystem.
                                </p>
                                <button className="button-primary button" title="Coming Soon" disabled>Learn More
                                </button>
                                <Accordion>
                                    <Card>
                                        <Card.Header>
                                            <p>
                                                Token utility and Value accrual
                                            </p>
                                            <ContextAwareToggle eventKey="0">Click me!</ContextAwareToggle>
                                        </Card.Header>
                                        <Accordion.Collapse eventKey="0">
                                            <Card.Body>Hello! I'm the body</Card.Body>
                                        </Accordion.Collapse>
                                    </Card>
                                    <Card>
                                        <Card.Header>
                                            <p>
                                                Token utility and Value accrual
                                            </p>
                                            <ContextAwareToggle eventKey="1">Click me!</ContextAwareToggle>
                                        </Card.Header>
                                        <Accordion.Collapse eventKey="1">
                                            <Card.Body>Persistence will be conducting a public sale/IEO in March 2021.
                                                More details around the XPRT token sale will be released shortly.
                                            </Card.Body>
                                        </Accordion.Collapse>
                                    </Card>
                                </Accordion>
                            </div>
                        </div>
                        <div className="col-md-6 text-center">
                            <img src={xprt_bg} alt="xprt_bg"/>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
export default Xprt;