import React from "react";
import xprt_bg from "../../assets/images1/xprt_bg.svg";
const Xprt = () => {
    return (
        <>
            <section className="xprt-section" id="section-xprt">
                <div className="container">
                    <h3 className="section-title">X<span>P</span>RT Token</h3>
                    <div className="row">
                        <div className="col-md-6 info-section">
                            <div className="info">
                                <p>The XPRT token is primarily a governance token for the Persistence chain. Once the
                                    Persistence mainnet is launched, token holders will be able to stake XPRT tokens to
                                    passively earn more XPRT. XPRT token also plays the role of a ‘work token’, allowing
                                    the stakers to produce cash flows in correlation with the transaction volume
                                    generated by dApps in the Persistence ecosystem.
                                </p>
                            </div>
                        </div>
                        <div className="col-md-6 text-center">
                            <img src={xprt_bg} alt="xprt_bg"/>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
export default Xprt;